name: Preview build

on:
  pull_request:
    branches: ['main']

jobs:
  typecheck:
    name: Typecheck
    steps:
      - uses: eas/checkout
      - uses: eas/use_npm_token
      - uses: eas/install_node_modules
      - name: Typecheck
        run: npm run typecheck

  build_android:
    name: Build Android preview
    needs: [typecheck]
    type: build
    params:
      platform: android
      profile: preview
